services:
  db:
    image: postgres:15
    container_name: postgres_glocation
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: glocationdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_glocation
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://admin:admin123@db:5432/glocationdb"
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: frontend_glocation
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install --include=dev && npm run dev -- --host"

volumes:
  db_data:
